# Generated by Django 5.1.4 on 2024-12-25 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0002_alter_custommanager_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custommanager',
            options={'permissions': [('notification_list', 'notification list'), ('notification_detail', 'notification detail'), ('notification_create', 'notification create'), ('notification_delete', 'notification delete'), ('contact_list', 'contact list'), ('contact_detail', 'contact detail'), ('contact_delete', 'contact delete'), ('manager_list', 'manager list'), ('manager_detail', 'manager detail'), ('manager_create', 'manager create'), ('manager_delete', 'manager delete'), ('user_list', 'user list'), ('user_detail', 'user detail'), ('user_delete', 'user delete'), ('task_list', 'task list'), ('task_detail', 'task detail'), ('transaction_detail', 'transaction detail')]},
        ),
    ]
